---
- name: Update OCP_VM_CPUS
  hosts: localhost
  gather_facts: false
  become: false
  vars:
     # vm_inventory_hostname
     # vm_namespace
  
  tasks:
    - name: Update {{ vm_inventory_hostname }} in  {{ vm_namespace }} with {{ ocp_vm_cpu_cores }} cores and {{ ocp_vm_cpu_sockets }}
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        validate_certs: false
        name: "{{ vm_inventory_hostname }}"
        namespace: "{{ vm_namespace }}"
        labels:
           automated: by-ansible
        spec: 
          domain:
           cpu: 
              cores: "{{ ocp_vm_cpu_cores }}"
              sockets: "{{ ocp_vm_cpu_sockets }}"
- name: Include Reboot Playbook if needed
  ansible.builtin.import_playbook: ocp_vm_restart.yaml
  vars:
    wantedstate: Reboot
  when: reboot_now == "yes"  