---
- name: Update OCP_VM_CPUS
  hosts: localhost
  gather_facts: false
  become: false
  vars:
     # vm_inventory_hostname
     # vm_namespace
  
  
  tasks:
    - name: Update {{ vm_inventory_hostname }} in {{vm_namespace}} with {{ ocp_vm_cpu_cores }} and {{ ocp_vm_cpu_sockets }}
       redhat.openshift_virtualization.kubevirt_vm:
         name: "{{ vm_inventory_hostname }}"
         namespace: "{{ vm_namespace }}"
         spec: 
           domain:
              cpu: 
                cores: "{{ ocp_vm_cpu_cores }}"
    
    
