---
- name: Gather CPU,Disk,and MEM data on running vm
  hosts: localhost
  gather_facts: false
  become: false
  vars:
     # vm_inventory_hostname
  
  
  tasks:
    - block:
        - name: Gather underlying facts from K8 definition file
          redhat.openshift_virtualization.kubevirt_vm_info:
            name: "{{ vm_inventory_hostname }}"
            namespace: vmexamples
            wait: true 
          register: ocp_virt_vm_info
    
        - name: Debug ocp vm facts
          ansible.builtin.debug:
            var: ocp_virt_vm_info['resources'][0]['spec']['template']['spec']['domain']['cpu']
        - name: Debug ocp vm facts
          ansible.builtin.debug:
            msg: "{{ ocp_virt_vm_info['resources'][0]['spec']['template']['spec']['domain']['resources']['requests'] }}"
            
    # We can define specific if we want to narrow it down
        - name: Register Fact to controller Cache
          ansible.builtin.set_fact:
            ocp_cfg_cpu: "{{ ocp_virt_vm_info['resources'][0]['spec']['template']['spec']['domain']['cpu'] }}"
          delegate_to: "{{ vm_inventory_hostname }}"  
          delegate_facts: true
          cacheable: yes
      delegate_to: localhost 
