---
- name: Expand disk space on a VM 
  hosts: localhost
  gather_facts: false
  become: false
  vars: 
    # pvc_name
    # vmexamples 
    # size 

  tasks:

# gather pvc claim name 
# expand pvc claim
    - name: expand PVC claim
      community.kubevirt.kubevirt_pvc:
        name: 'move-webapp-vmware-vm-1554529-6snxz'
        namespace: 'vmexamples'
        size: '21Gi'

# gather facts from OS for expanding disk 
# expand VM OS 