---
- name: Gather CPU,Disk,and MEM data on running vm
  hosts: localhost
  gather_facts: false
  become: true
  vars:
     # vm_inventory_hostname
  
  
  tasks:
    - block
      -  name: Gather underlying facts from K8 definition file
         redhat.openshift_virtualization.kubevirt_vm_info:
            name: "{{ vm_inventory_hostname }}"
            namespace: default
            wait: true 
         register: ocp_virt_vm_info
       
      -  name: Debug ocp vm facts
         ansbile.builtin.debug:
            var: ocp_virt_vm_info 
         verbosity: 2

    # We can define specific if we want to narrow it down
      -  name: Register Fact to controller Cache 
         ansible.builtin.set_fact:
           ocp_vm_config_yaml: "{{ ocp_virt_vm_info }}"
      delegate_to: localhost 
