---
- name: Gather CPU,Disk,and MEM data on running vm
  hosts: localhost,{{ vm_inventory_hostname }}
  gather_facts: false
  become: false
  vars:
     # vm_inventory_hostname
     # vm_namespace
  
  
  tasks:
    - block:
        - name: Gather underlying facts from K8 definition file for {{ vm_inventory_hostname }}
          redhat.openshift_virtualization.kubevirt_vm_info:
            name: "{{ vm_inventory_hostname }}"
            namespace: "{{ vm_namespace }}"
            wait: true 
          register: ocp_virt_vm_info
    
        - name: Debug ocp vm facts
          ansible.builtin.debug:
            var: ocp_virt_vm_info['resources'][0]['spec']['template']['spec']['domain']['cpu']['cores']
            verbosity: 1
        - name: Debug ocp vm facts
          ansible.builtin.debug:
            msg: "{{ ocp_virt_vm_info['resources'][0]['spec']['template']['spec']['domain']['resources']['requests']['memory'] }}"
            verbosity: 1
    # We can define specific if we want to narrow it down
        - name: Register facts of {{ vm_inventory_hostname }} to controller fact cache
          ansible.builtin.set_fact:
            ocp_cfg_cpu_cores: "{{ ocp_virt_vm_info['resources'][0]['spec']['template']['spec']['domain']['cpu']['cores'] }}"
            ocp_cfg_cpu_sockets: "{{ ocp_virt_vm_info['resources'][0]['spec']['template']['spec']['domain']['cpu']['sockets'] }}"
            ocp_cfg_memory: "{{ ocp_virt_vm_info['resources'][0]['spec']['template']['spec']['domain']['resources']['requests']['memory'] }}"
            cacheable: yes
          delegate_to: "{{ vm_inventory_hostname }}"  
          delegate_facts: true
        
      delegate_to: localhost 
      run_once: true
 
