---
- name: OCP VM Report
  hosts: localhost
  gather_facts: false
  become: false
  #vars:

  tasks: 
  
  - name: Create a PVC Claim for Reports Pod 
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: reportspvc
          namespace: vmexamples
        spec:
          accessModes:
            - ReadWriteOnce
          volumeMode: Filesystem
          resources:
            requests:
              storage: 500Mi
      wait: yes
    #register: volname

  - name: Get an PVC Claim Info
    kubernetes.core.k8s_info:
     api_version: v1
     kind: PersistentVolumeClaim
     name: reportspvc
     namespace: vmexamples 
    register: volname

  - name: Debug volume name facts
    ansible.builtin.debug:
      var: volname['resources'][0]['spec']['volumeName']

  - name: Setfact 
    ansible.builtin.set_fact:
      volume_name: "{{ volname['resources'][0]['spec']['volumeName'] }}"
  
  - name: Debug volume_name
    ansible.builtin.debug:
      var: volume_name

  - name: Create a pod for Reports
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: reportspod-1
          namespace: vmexamples
          labels:
            app: reportspod
            createdby: Ansible
        spec:
          containers:
          - name: reportspod
            image: quay.io/samander/nginx-report-base:latest
            volumeMounts: 
            - name: reportspvc
              mountPath: /var/report
              
            ports: 
              - containerPort: 8080
          volumes: 
            - name: reportspvc
              emptyDir:
                sizeLimit: 200Mi
              
              #persistentVolumeClaim: 
               # claimName: reportspvc


  - name: Create a service for Reports Pod 
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service 
        metadata:
          name: reportsweb
          namespace: vmexamples
          labels:
            app: reportspod
            createdby: Ansible
            service: reportsweb 
        spec: 
          selector: 
            app: reportspod 
            service: reportsweb 
          ports: 
            - protocol: TCP 
              port: 80
              targetPort: 8080
            
        

          

          #   volumeMounts: 
          #   - mountPath: 
          #     name: report
          # volumes: 
          # - name: report-volume
          #   emptyDir: 
          #     sizelimit: 500Mi
            

  #  - name: Launch Container and Create directory for Reports
  #    block:
  #    - name: OS Report directory is present
  #      file:
  #        path: "{{ home_dir }}/reports/css"
  #        owner: "{{ report_user }}"
  #        state: directory

  #   - name: CSS is present on remote host
  #       copy:
  #         src: CSS/main.css
  #         dest: "{{ home_dir }}/reports/css/main.css"

  #   - name: OS Report container is launched
  #       containers.podman.podman_container:
  #         name: report
  #         image: quay.io/samander/nginx-report-base:latest
  #         state: started
  #         volume:
  #           - "{{ home_dir }}/reports:/var/report:Z"
  #         ports:
  #           - "{{ target_port }}:8080"
  #     run_once: True
  #     delegate_to: "{{ container_host }}"