---
- name: Update OCP_VM_CPUS
  hosts: localhost
  gather_facts: false
  become: false
  vars:
     # vm_inventory_hostname
     # vm_namespace
  
  
  tasks:
    - name: Update VM
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        validate_certs: false
        name: "{{ vm_inventory_hostname }}"
        namespace: "{{ vm_namespace }}"
        labels:
           automated: byansible
        spec: 
          domain:
           cpu: 
              cores: "{{ ocp_vm_cpu_cores }}"
    
    
