---
- name: OSV_VM_State Control  
  hosts: localhost
  gather_facts: false
  become: false
  vars:
     # vm_inventory_hostname
     # vm_namespace
  
  
  tasks:
    - block: 
       - name: Debug multilist
         ansible.builtin.debug:
          msg: 'List of Servers to be {{wantedstate}} {{ target_list }}'
      
       - name: Stopping Servers 
         redhat.openshift_virtualization.kubevirt_vm:
           state: present
           validate_certs: false
           name: "{{ item }}"
           namespace: "{{ vm_namespace }}"
           running: false 
         loop: "{{ target_list }}"
         when: wantedstate == "Stop" or wantedstate == "Reboot"
       
       - name: Starting Servers
         redhat.openshift_virtualization.kubevirt_vm:
           state: present
           validate_certs: false
           name: "{{ item }}"
           namespace: "{{ vm_namespace }}"
           running: true 
         loop: "{{ target_list }}"
         when: wantedstate == "Start" or wantedstate == "Reboot"
      