---
- name: OSV_VM_State Control  
  hosts: localhost
  gather_facts: false
  become: false
  vars:
     # vm_inventory_hostname
     # vm_namespace
  
  
  tasks:
    - name: Debug multilist
      ansible.builtin.debug:
        var: multiple_targets
   
    - name: Stop {{ item.[0] }} in {{ vm_namespace }} 
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        validate_certs: false
        name: "{{ item.[0] }}"
        namespace: "{{ vm_namespace }}"
        running: false 
      loop: "{{ multiple_targets }}"  
      when: wantedstate == "Stop" or wantedstate == "Reboot"
    
    - name: Start {{ item.[0] }} in  {{ vm_namespace }} 
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        validate_certs: false
        name: "{{ item.[0] }}"
        namespace: "{{ vm_namespace }}"
        running: true 
      loop: "{{ multiple_targets }}"
      when: wantedstate == "Start" or wantedstate == "Reboot"
             
