---
- name: Update OCP_VM_CPUS
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    osv_virt_vm_disk_claimname: "{{ disk_claimname }}"
    osv_vm_namespace: "{{ vm_inventory_hostname | split ('-') | first }}"
    osv_vm_hostname: "{{ vm_inventory_hostname | split ('-') | last }}"
    osv_vm_disk_size: "{{ disk_size }}"
   
  roles:
    - role: osv_vm_disk_expand
