- block:
   - name: Gather underlying facts from K8 definition file for {{ vm_inventory_hostname }}
     redhat.openshift_virtualization.kubevirt_vm_info:
       name: "{{ osv_vm_hostname }}"
       namespace: "{{ osv_vm_namespace }}"
     register: osv_virt_vm_info
   - name: debug vars
     ansible.builtin.debug:
       var: osv_virt_vm_info['resources'][0]['spec']['template']['spec']['volumes'][0]['persistentVolumeClaim']['claimName']
       verbosity: 2
   - name: Set claim name fact
     ansible.builtin.set_fact:
       osv_virt_vm_disk_claimname: "{{ osv_virt_vm_info['resources'][0]['spec']['template']['spec']['volumes'][0]['persistentVolumeClaim']['claimName'] }}"
   - name: debug var
     ansible.builtin.debug:
       var: osv_virt_vm_disk_claimname
       verbosity: 2
   - name: Expand {{ osv_virt_vm_disk_claimname }} on {{ vm_inventory_hostname }} to {{osv_vm_disk_size}}
     redhat.openshift.k8s:
        state: patched
        definition:
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: "{{ osv_virt_vm_disk_claimname }}"
            namespace: "{{ osv_vm_namespace }}"
          spec:
            resources:
              requests:
                storage: "{{ osv_vm_disk_size }}"

  delegate_to: localhost
  run_once: true