- name: Debug multilist
  ansible.builtin.debug:
   msg: 'List of Servers to be {{wantedstate}} {{ target_list }}'
- name: Create list of servername and namespace for {{ wantedstate }}
  ansible.builtin.set_fact:
   final_list: "{{ target_list | map('split','-') }}"
- name: Debug final_list
  ansible.builtin.debug:
   msg: " {{ final_list }} "
   verbosity: 2
- name: Stopping Servers
  redhat.openshift_virtualization.kubevirt_vm:
   state: present
   validate_certs: false
   name: "{{ item[1] }}"
   namespace: "{{ item[0] }}"
   running: false
  loop: "{{ final_list }}"
  when: wantedstate == "Stop" or wantedstate == "Reboot"

- name: Starting Servers
  redhat.openshift_virtualization.kubevirt_vm:
   state: present
   validate_certs: false
   name: "{{ item[1] }}"
   namespace: "{{ item[0] }}"
   running: true
  loop: "{{ final_list }}"
  when: wantedstate == "Start" or wantedstate == "Reboot"
